services:
  koel:
    image: phanan/koel
    depends_on:
      - database
    ports:
      - 3050:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=R6dp!knD@
      - DB_DATABASE=koel
    volumes:
      - ./music:/music
      - ./covers:/var/www/html/public/img/covers
      - ./search_index:/var/www/html/storage/search-indexes

  database:
    image: mariadb:10.11
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=8RS6GgxAJCn9konA
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=R6dp!knD@

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
